version: '3'

services:
  db:
    image: postgres
    container_name: moebius-db
    ports:
      - "5432:5432"
    volumes:
      - ./test/db/create:/docker-entrypoint-initdb.d/
    command: postgres -c config_file=/etc/postgresql/postgresql.conf 
    environment:
      POSTGRES_HOST: /var/run/postgresql
      POSTGRES_PASSWORD: postgres
