name: Elixir CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest

    env:
      MIX_ENV: test
      PGPASSWORD: postgres
      DB_HOST: db

    services:
      db:
        image: postgres
        ports: ['5432:5432']
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: moebius_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - uses: actions/checkout@v3

    - name: Create database
      run: |
        psql -h localhost -U postgres -c "CREATE DATABASE moebius_test;"

    - name: Setup Elixir
      uses: erlef/setup-beam@v1
      with:
        version-type: strict
        version-file: .tool-versions

    - name: Restore dependencies cache
      uses: actions/cache@v3
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-

    - name: Install dependencies
      run: |
        mix local.rebar --force
        mix local.hex --force
        mix deps.get

    - name: Set up test data
      run: |
        mix moebius.migrate
        mix moebius.seed

    - name: Check warnings
      run: |
        mix compile --warnings-as-errors

    - name: Run tests
      run: |
        mix test

    - name: Check code quality, security and format
      run: |
        mix quality --strict
